# Generated by Django 4.0.4 on 2022-04-22 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone_numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_num', models.CharField(default='NULL', max_length=100, null=True, verbose_name='Ф.И.О.')),
            ],
        ),
        migrations.CreateModel(
            name='AllUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(default='NULL', max_length=100, verbose_name='Ф.И.О.')),
                ('date_of_birth', models.CharField(default='NULL', max_length=100, verbose_name='День рожденья')),
                ('citizenship', models.CharField(default='NULL', max_length=300, verbose_name='Гражданство')),
                ('passport', models.CharField(default='NULL', max_length=300, verbose_name='Пасспорт')),
                ('date_of_get_passport', models.CharField(default='NULL', max_length=300, verbose_name='Дата выдачи паспорта:')),
                ('organ_who_gave_passport', models.CharField(default='NULL', max_length=300, verbose_name='Орган, выдавший паспорт')),
                ('department_code', models.CharField(default='NULL', max_length=300, unique=True, verbose_name='Код подразделения')),
                ('registration_address_in_passport', models.CharField(default='NULL', max_length=300, verbose_name='Адрес регистрации (по паспорту)')),
                ('registration_address_on_living_place', models.CharField(default='NULL', max_length=300, verbose_name='Адрес регистрации по месту пребывания')),
                ('registration_address_in_fact', models.CharField(default='NULL', max_length=300, verbose_name='Адрес фактического проживания')),
                ('phone_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleBot.phone_numbers')),
            ],
            options={
                'verbose_name': 'Юзер',
                'verbose_name_plural': 'Все Юзеры',
            },
        ),
    ]
