# Generated by Django 4.0.4 on 2022-04-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleBot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone_numbers',
            options={'verbose_name': 'Телефон', 'verbose_name_plural': 'Телефоны'},
        ),
    ]
