# Generated by Django 4.0.4 on 2022-04-22 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teleBot', '0002_alter_phone_numbers_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
        migrations.RemoveField(
            model_name='allusers',
            name='phone_num',
        ),
        migrations.DeleteModel(
            name='Phone_numbers',
        ),
        migrations.AddField(
            model_name='phonenumbers',
            name='phone_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleBot.allusers'),
        ),
    ]
