# Generated by Django 4.0.4 on 2022-04-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleBot', '0004_phonenumbers_owner_alter_allusers_department_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allusers',
            name='id_tele',
            field=models.CharField(default='NULL', max_length=15, unique=True, verbose_name='id tele'),
        ),
    ]
