# Generated by Django 4.0.4 on 2022-04-22 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teleBot', '0005_allusers_id_tele'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelativeOwnerPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NULL', max_length=100, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Родственник',
                'verbose_name_plural': 'Родственники',
            },
        ),
        migrations.AddField(
            model_name='phonenumbers',
            name='relative_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleBot.relativeownerphone'),
        ),
    ]
