# Generated by Django 4.0.4 on 2022-04-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleBot', '0007_alter_phonenumbers_relative_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allusers',
            name='passport',
        ),
        migrations.AddField(
            model_name='allusers',
            name='birthplace',
            field=models.CharField(default='NULL', max_length=100, verbose_name='Место рождения'),
        ),
        migrations.AddField(
            model_name='allusers',
            name='passport_num',
            field=models.CharField(default='NULL', max_length=300, verbose_name='Пасспорт номер'),
        ),
        migrations.AddField(
            model_name='allusers',
            name='passport_series',
            field=models.CharField(default='NULL', max_length=300, verbose_name='Пасспорт серия'),
        ),
        migrations.AddField(
            model_name='allusers',
            name='phone_num',
            field=models.CharField(default='NULL', max_length=100, verbose_name='Номер телефона'),
        ),
    ]
