# Generated by Django 4.0.4 on 2022-04-23 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleBot', '0009_allusers_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allusers',
            old_name='access',
            new_name='questionnaireExist',
        ),
    ]
